### ISSUE TITLE
Error in fn(x, ...) : Downdated VtV is not positive definite

### ISSUE THREAD

**Issue by Jingzcode** [jcbeer/longCombat#4]
Hello,

I'm using LongCombat on a study with 20 subjects, twice imaged. And within 20 subjects, they are assigned into 2 scanners. In my model, I only set (1|Subject) as random effect and 'age' as fixed effect. The feature is a count number so it's quite right skewed.

And when I applying this function, always shows the error in the title. Exploring your code, I found longCombat is based on lmer() function and REML = TRUE. I guess "glmer" or "REML = False" is suitable for my case. 

Would u please give me any suggestion for this study? like longitudinal combat based on glmm?

Thanks.
Best regards.

**Comment by jcbeer** [comment]
Hi, 

So the imaging features you are modeling as outcomes are right skewed count variables (I assume you have multiple features as that is required for ComBat)? 

You could try using ComBat-seq, originally developed for RNA seq data but uses a negative binomial model which could be appropriate for the count data you have. There is not a mixed model implementation of it, as far as I know, unfortunately, but you could try including subject as a fixed effect. **https://rdrr.io/bioc/sva/man/ComBat_seq.html**

Regarding the error message, you could also check for collinearity in your design matrix. Make sure your variables are of the right class, for example make sure age is numeric and not a factor -- But even if this was the problem, it sounds like longCombat is not appropriate for your current data distribution.

Otherwise you could consider transforming the outcome so that it is more normally distributed (taking log for example) and then using longCombat, but I understand that transforming the outcome may not be desirable. 

Finally, you could just not do ComBat harmonization and instead use a negative binomial glmm and use batch as fixed effect. 

There may be other ways to approach it but those are some ideas. 

Joanne
